apiVersion: v1
kind: Service
metadata:
  name: vsftpd
  labels:
    app: vsftpd
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  ports:
  - port: 21
    name: vsftpd
  - port: 20
    name: vsftpd2
  - port: 10020
    name: passive
  - port: 10021
    name: passive2
  selector:
      app: vsftpd
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsftpd
  labels:
    app: vsftpd
spec:
  selector:
    matchLabels:
      app: vsftpd
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      serviceAccount: pod-service-access
      containers:
      - image: ftps-img
        imagePullPolicy: Never
        name: vsftpd
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 10020
        - containerPort: 10021
